- name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./eduplay-backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/eduplay-backend:latest

      - name: Build & Push Primary Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./eduplay-primary
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/eduplay-primary:latest